# Generated by Django 3.1.4 on 2020-12-12 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('lower_limit', models.FloatField()),
                ('upper_limit', models.FloatField()),
            ],
        ),
    ]
