# Generated by Django 3.1.4 on 2020-12-12 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='name',
            new_name='symbol',
        ),
    ]
