# Generated by Django 3.1.4 on 2020-12-21 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_asset_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='lower_limit',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='upper_limit',
        ),
        migrations.AddField(
            model_name='asset',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='TrackedAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lower_limit', models.FloatField(default=0)),
                ('upper_limit', models.FloatField(default=0)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.asset')),
            ],
        ),
    ]
